spring:
  application:
    name: server-unsplash

  datasource:
    url: jdbc:postgresql://localhost:5432/${PSQL_DATABASE}
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true